apiVersion: v1
kind: Service
metadata:
  name: pod-tracker-service
spec:
  type: LoadBalancer  
  selector:
    app: pod-tracker
  ports:
  - port: 80          
    targetPort: 3000  
    protocol: TCP